### ISSUE TITLE
Changing data in view?

### ISSUE THREAD

**Issue by stephen-bunn** [williballenthin/python-pyqt5-hexview#4]
Could you give a quick example on how to change the data within the view after creating the widget?
Currently setting the model's data and calling update doesn't work for me.

**Comment by williballenthin** [comment]
hey @ritashugisha 

there isn't a simple example of this since (unfortunately) i didn't design the library for editing.

here's what i *think* might work:

  - update `view._buf`
  - update `view.model._buf`
  - call `view.model._emit_data_changed(start-index, end-index)`

as you can see, you have to reach into some members that aren't meant to be public. i'd be interested to hear if you're able to get this to work!

**Comment by stephen-bunn** [comment]
I never tried to get this to work. But I'm thinking your suggestion should get people close to a solution.
